spring:
  datasource:
    url: jdbc:h2:mem:currencydb
    driver-class-name: org.h2.Driver
    username: ibm
    password: ibm
  zipkin:
    base-url: http://192.168.99.100:9411
  sleuth:
    sampler:
      probability: 1.0
    trace-id128: true
    
   
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  application:
    name: manage-currency
    

server:
  port: 8090
  
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.int}
    lease-renewal-interval-in-seconds: 2
    lease-expiration-duration-in-seconds: 5
    prefer-ip-address: true
    metadata-map:
      zone: A
  client:
    register-with-eureka: true
    fetch-registry: true
    prefer-same-zone-eureka: true
    service-url:
      defaultZone : http://192.168.99.100:8100/eureka
      
